return {
	Average_NPC_Amount = 5,
	Average_Rat_Amount = 5,

	--// from a 100
	Barricade_Chance = 10,
	DeadBody_Chance = 25,

	--// idk what a spawn node is supposed to contain
	SpawnNode = {},

	Mutations = {
		RandomMutate = {
			Aggressive_Mutation_Chance = 45, --// chance an npc bcomes aggressive randomly
			Terminal_Mutation_Chance = 50, --// chance an npc dies within a timeframe
		},

		AnotherRandomMutate = {
			Aggressive_Mutation_Chance = 35, --// chance an npc bcomes aggressive randomly
			Terminal_Mutation_Chance = 20, --// chance an npc dies within a timeframe
		},
	},
}
