local TOOL_TIP_CONFIG = {
	deathTollCollected = {
		text = "A Burned Body",
		color = Color3.fromRGB(236, 253, 235),
	},

	collectByBurning = {
		text = "Burn It!",
		color = Color3.fromRGB(126, 16, 16),
	},

	aggressive = {
		text = "Aggressive!",
		color = Color3.fromRGB(126, 16, 16),
	},

	wandering = {
		text = "Civilian",
		color = Color3.fromRGB(171, 226, 183),
	},

	goodFlower = {
		text = "Heal!",
		color = Color3.fromRGB(119, 241, 62),
	},

	basicFlower = {
		text = "Flower.",
		color = Color3.fromRGB(255, 255, 255),
	},

	badFlower = {
		text = "Wrong Flower!",
		color = Color3.fromRGB(54, 3, 3),
	},
}

return TOOL_TIP_CONFIG
